// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.9
// source: profanityfilter.proto

package registered_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProfanityFilterService_Validate_FullMethodName = "/accelbyte.profanityfilter.registered.v1.ProfanityFilterService/Validate"
)

// ProfanityFilterServiceClient is the client API for ProfanityFilterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfanityFilterServiceClient interface {
	Validate(ctx context.Context, in *ExtendProfanityValidationRequest, opts ...grpc.CallOption) (*ExtendProfanityValidationResponse, error)
}

type profanityFilterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfanityFilterServiceClient(cc grpc.ClientConnInterface) ProfanityFilterServiceClient {
	return &profanityFilterServiceClient{cc}
}

func (c *profanityFilterServiceClient) Validate(ctx context.Context, in *ExtendProfanityValidationRequest, opts ...grpc.CallOption) (*ExtendProfanityValidationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExtendProfanityValidationResponse)
	err := c.cc.Invoke(ctx, ProfanityFilterService_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfanityFilterServiceServer is the server API for ProfanityFilterService service.
// All implementations should embed UnimplementedProfanityFilterServiceServer
// for forward compatibility.
type ProfanityFilterServiceServer interface {
	Validate(context.Context, *ExtendProfanityValidationRequest) (*ExtendProfanityValidationResponse, error)
}

// UnimplementedProfanityFilterServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProfanityFilterServiceServer struct{}

func (UnimplementedProfanityFilterServiceServer) Validate(context.Context, *ExtendProfanityValidationRequest) (*ExtendProfanityValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedProfanityFilterServiceServer) testEmbeddedByValue() {}

// UnsafeProfanityFilterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfanityFilterServiceServer will
// result in compilation errors.
type UnsafeProfanityFilterServiceServer interface {
	mustEmbedUnimplementedProfanityFilterServiceServer()
}

func RegisterProfanityFilterServiceServer(s grpc.ServiceRegistrar, srv ProfanityFilterServiceServer) {
	// If the following call pancis, it indicates UnimplementedProfanityFilterServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProfanityFilterService_ServiceDesc, srv)
}

func _ProfanityFilterService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendProfanityValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfanityFilterServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProfanityFilterService_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfanityFilterServiceServer).Validate(ctx, req.(*ExtendProfanityValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfanityFilterService_ServiceDesc is the grpc.ServiceDesc for ProfanityFilterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfanityFilterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.profanityfilter.registered.v1.ProfanityFilterService",
	HandlerType: (*ProfanityFilterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _ProfanityFilterService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profanityfilter.proto",
}
