// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.21.9
// source: profanityfilter.proto

package registered_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ExtendProfanityValidationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`   // the value needs to be validated
	UserId        string                 `protobuf:"bytes,2,opt,name=userId,proto3" json:"userId,omitempty"` // user id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendProfanityValidationRequest) Reset() {
	*x = ExtendProfanityValidationRequest{}
	mi := &file_profanityfilter_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendProfanityValidationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendProfanityValidationRequest) ProtoMessage() {}

func (x *ExtendProfanityValidationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_profanityfilter_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendProfanityValidationRequest.ProtoReflect.Descriptor instead.
func (*ExtendProfanityValidationRequest) Descriptor() ([]byte, []int) {
	return file_profanityfilter_proto_rawDescGZIP(), []int{0}
}

func (x *ExtendProfanityValidationRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *ExtendProfanityValidationRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ExtendProfanityValidationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IsProfane     bool                   `protobuf:"varint,1,opt,name=isProfane,proto3" json:"isProfane,omitempty"` // indicates whether the value is profane or not
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`      // if valid is false, message will provide the detailed error message
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExtendProfanityValidationResponse) Reset() {
	*x = ExtendProfanityValidationResponse{}
	mi := &file_profanityfilter_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExtendProfanityValidationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExtendProfanityValidationResponse) ProtoMessage() {}

func (x *ExtendProfanityValidationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_profanityfilter_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExtendProfanityValidationResponse.ProtoReflect.Descriptor instead.
func (*ExtendProfanityValidationResponse) Descriptor() ([]byte, []int) {
	return file_profanityfilter_proto_rawDescGZIP(), []int{1}
}

func (x *ExtendProfanityValidationResponse) GetIsProfane() bool {
	if x != nil {
		return x.IsProfane
	}
	return false
}

func (x *ExtendProfanityValidationResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_profanityfilter_proto protoreflect.FileDescriptor

const file_profanityfilter_proto_rawDesc = "" +
	"\n" +
	"\x15profanityfilter.proto\x12'accelbyte.profanityfilter.registered.v1\"P\n" +
	" ExtendProfanityValidationRequest\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\tR\x06userId\"[\n" +
	"!ExtendProfanityValidationResponse\x12\x1c\n" +
	"\tisProfane\x18\x01 \x01(\bR\tisProfane\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xbc\x01\n" +
	"\x16ProfanityFilterService\x12\xa1\x01\n" +
	"\bValidate\x12I.accelbyte.profanityfilter.registered.v1.ExtendProfanityValidationRequest\x1aJ.accelbyte.profanityfilter.registered.v1.ExtendProfanityValidationResponseB\x86\x01\n" +
	"+net.accelbyte.profanityfilter.registered.v1P\x01Z+accelbyte.net/profanityfilter/registered_v1\xaa\x02'AccelByte.ProfanityFilter.Registered.V1b\x06proto3"

var (
	file_profanityfilter_proto_rawDescOnce sync.Once
	file_profanityfilter_proto_rawDescData []byte
)

func file_profanityfilter_proto_rawDescGZIP() []byte {
	file_profanityfilter_proto_rawDescOnce.Do(func() {
		file_profanityfilter_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_profanityfilter_proto_rawDesc), len(file_profanityfilter_proto_rawDesc)))
	})
	return file_profanityfilter_proto_rawDescData
}

var file_profanityfilter_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_profanityfilter_proto_goTypes = []any{
	(*ExtendProfanityValidationRequest)(nil),  // 0: accelbyte.profanityfilter.registered.v1.ExtendProfanityValidationRequest
	(*ExtendProfanityValidationResponse)(nil), // 1: accelbyte.profanityfilter.registered.v1.ExtendProfanityValidationResponse
}
var file_profanityfilter_proto_depIdxs = []int32{
	0, // 0: accelbyte.profanityfilter.registered.v1.ProfanityFilterService.Validate:input_type -> accelbyte.profanityfilter.registered.v1.ExtendProfanityValidationRequest
	1, // 1: accelbyte.profanityfilter.registered.v1.ProfanityFilterService.Validate:output_type -> accelbyte.profanityfilter.registered.v1.ExtendProfanityValidationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_profanityfilter_proto_init() }
func file_profanityfilter_proto_init() {
	if File_profanityfilter_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_profanityfilter_proto_rawDesc), len(file_profanityfilter_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_profanityfilter_proto_goTypes,
		DependencyIndexes: file_profanityfilter_proto_depIdxs,
		MessageInfos:      file_profanityfilter_proto_msgTypes,
	}.Build()
	File_profanityfilter_proto = out.File
	file_profanityfilter_proto_goTypes = nil
	file_profanityfilter_proto_depIdxs = nil
}
