// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.18.1
// source: profanityfilter.proto

package registered_v1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ProfanityFilterServiceClient is the client API for ProfanityFilterService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProfanityFilterServiceClient interface {
	Validate(ctx context.Context, in *ExtendProfanityValidationRequest, opts ...grpc.CallOption) (*ExtendProfanityValidationResponse, error)
}

type profanityFilterServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewProfanityFilterServiceClient(cc grpc.ClientConnInterface) ProfanityFilterServiceClient {
	return &profanityFilterServiceClient{cc}
}

func (c *profanityFilterServiceClient) Validate(ctx context.Context, in *ExtendProfanityValidationRequest, opts ...grpc.CallOption) (*ExtendProfanityValidationResponse, error) {
	out := new(ExtendProfanityValidationResponse)
	err := c.cc.Invoke(ctx, "/accelbyte.profanityfilter.registered.v1.ProfanityFilterService/Validate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProfanityFilterServiceServer is the server API for ProfanityFilterService service.
// All implementations must embed UnimplementedProfanityFilterServiceServer
// for forward compatibility
type ProfanityFilterServiceServer interface {
	Validate(context.Context, *ExtendProfanityValidationRequest) (*ExtendProfanityValidationResponse, error)
	mustEmbedUnimplementedProfanityFilterServiceServer()
}

// UnimplementedProfanityFilterServiceServer must be embedded to have forward compatible implementations.
type UnimplementedProfanityFilterServiceServer struct {
}

func (UnimplementedProfanityFilterServiceServer) Validate(context.Context, *ExtendProfanityValidationRequest) (*ExtendProfanityValidationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedProfanityFilterServiceServer) mustEmbedUnimplementedProfanityFilterServiceServer() {
}

// UnsafeProfanityFilterServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProfanityFilterServiceServer will
// result in compilation errors.
type UnsafeProfanityFilterServiceServer interface {
	mustEmbedUnimplementedProfanityFilterServiceServer()
}

func RegisterProfanityFilterServiceServer(s grpc.ServiceRegistrar, srv ProfanityFilterServiceServer) {
	s.RegisterService(&ProfanityFilterService_ServiceDesc, srv)
}

func _ProfanityFilterService_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExtendProfanityValidationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProfanityFilterServiceServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/accelbyte.profanityfilter.registered.v1.ProfanityFilterService/Validate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProfanityFilterServiceServer).Validate(ctx, req.(*ExtendProfanityValidationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProfanityFilterService_ServiceDesc is the grpc.ServiceDesc for ProfanityFilterService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProfanityFilterService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "accelbyte.profanityfilter.registered.v1.ProfanityFilterService",
	HandlerType: (*ProfanityFilterServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Validate",
			Handler:    _ProfanityFilterService_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "profanityfilter.proto",
}
